spring:
  profiles:
    active: local
    include: secret
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    hiddenmethod: # @DeleteMapping 사용 위해
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      #  show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug

custom:
  profileImage:
    defaultUrl: "https://matzip-img.s3.ap-northeast-2.amazonaws.com/profileImages/defaultProfile.png"