spring:
  profiles:
    active: local
    include: secret
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug